### ISSUE TITLE
cannot find libmosek64.so.8.1

### ISSUE THREAD

**Issue by susierao** [UCLA-StarAI/NaCL#5]
Dear NaCL team, 
I followed the installation tips here on linux and still have the following error in python:

![image](https://user-images.githubusercontent.com/19934422/91314552-f80eb900-e7b6-11ea-9542-b1daaa89ed7b.png)
Basically python does not see mosek, but mosek -f runs.

Thank you.

**Comment by khosravipasha** [comment]
Hi,  Thank for reaching out. 

I have not encountered this specific error myself, but my guess is that MOSEK is not setup correctly for python. What is your python version?

For using NaCL, you do not necessarily need to be able to load Mosek in python. GPKit has an option for "mosek_cli" backend which calls mosek through command line. Since you can run 'mosek -f' in command line, then this option should work. You can check this by running our [demo notebook](https://github.com/UCLA-StarAI/NaCL/blob/master/notebooks/demo.ipynb).

I have been meaning to [update to python3](https://github.com/UCLA-StarAI/NaCL/issues/3) and make an easier way to use NaCL such as [using docker](https://github.com/UCLA-StarAI/NaCL/issues/6), but have not had the chance yet.

**Comment by khosravipasha** [comment]
@susierao I just recenetly ported the code to python3 and new gpkit, mosek. It should be much easier to setup. And they
have fixed the issue with mosek.

Now you can try using the python3-refactor branch. 
https://github.com/UCLA-StarAI/NaCL/tree/python3-refactor
